### ISSUE TITLE
Spreadsheet generator is not working

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/schema-template-generator#4]
The When running the spreadsheet generator, I can load the UI, but when I choose Load all schemas I get the following error:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

I get the same error when choosing the Pre-select schemas, selecting the schemas and them going to the next stage.

I follow the instructions here to run it: https://github.com/HumanCellAtlas/hca-data-wrangling/blob/master/docs/wrangler_tool_survey.adoc#generating-custom-template-metadata-spreadsheet-template_generator_app-py

**Comment by zperova** [comment]
This is the output of the command line that I get when the error is displayed:
```
(spreadsheet2) C02X488AJHD2:generator zina$ python template_generator_app.py
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:22] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:22] "GET /static/js/common.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:22] "GET /static/css/index.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:22] "GET /static/js/index.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:22] "GET /static/images/hca_logo.png HTTP/1.1" 200 -
contributors is a recorded sub-property
publications is a recorded sub-property
funders is a recorded sub-property
[2019-05-30 12:17:28,305] ERROR in app: Exception on /load_all [GET]
Traceback (most recent call last):
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/spreadsheet2/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "template_generator_app.py", line 80, in load_full_schemas
    all_properties = _process_schemas()
  File "template_generator_app.py", line 340, in _process_schemas
    new_property["title"] = tab_config.lookup('meta_data_properties')[parent][key]['user_friendly']
KeyError: 'protocol_reagents'
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:28] "GET /load_all? HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/May/2019 12:17:28] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by zperova** [comment]
Has now been fixed.

**Comment by tawsif1** [comment]
> Has now been fixed.

how??
